name: Updater

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 19 * * *' # Run every day at midnight WIB
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          DC_KEY: ${{ secrets.DC_KEY}}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8bf56353bcb3a8e798b55b546b9619cf
          STEAM_API_KEY: ${{ secrets.ST_KEY}}
    steps:
      
    - name: Run updater.py
      env:
        HEADERS: ${{ secrets.DC_KEY }}
      run: |
         python updater.py

    - name: Commit and push if changed
      run: |
        git config user.name "Windstrom5"
        git config user.email "anggagant@gmail.com"
        git diff
        git add README.md generated-profile.png
        git commit -sm "workflow: update some magic~"
         git push
