name: Update steam playtime

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
   - cron: '0 19 * * *' # Run every day at midnight WIB

jobs:
  build:
    name: Update-steam-playtime
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_SECRET }}
      GIST_ID: 10c3b5ab143aff46464bb5dcd33bbcca
      STEAM_API_KEY: ${{ secrets.ST_KEY }}
      STEAM_ID: 76561198881808539
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Clone and run steam-box
        run: |-
          git clone https://github.com/YouEclipse/steam-box.git 
          cd steam-box && go build -o steam ./cmd/box/main.go
          mv ./steam ../ && cd .. && rm -rf steam-box/

      - name: Commit and push
        run: |-
          ./steam
          git config --global user.email "bot@github.com" && git config --global user.name "Steam-Bot"
          git diff
          git add README.md && git commit -m ":memo: update profile" || exit 0
          git pull && git push
